language: cpp

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - llvm-toolchain-3.9
    packages:
      - cmake-data
      - cmake
      - clang-3.9

compiler:
  - clang
  - gcc

install:
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi

script: mkdir build && cd build && cmake .. && make && make test
