language: cpp

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

compiler:
  - clang
  - gcc

script: mkdir build && cd build && cmake .. && make && make test
