language: cpp

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - clang-3.7

compiler:
  - clang
  - gcc

script: mkdir build && cd build && cmake .. && make && make test
